name: "Setup build"
description: "Setup environment for the build"
inputs: {}
outputs: {}
runs:
  using: "composite"
  steps:
    - name: Setup Go
      uses: actions/setup-go@0c52d547c9bc32b1aa3301fd7a9cb496313a4491 #v5.0.0
      with:
        go-version: 1.20.x
        cache: false
    - name: Cache go-build and mod
      uses: actions/cache@704facf57e6136b1bc63b828d79edcd491f0ee84 #v3.3.2
      with:
        path: |
          ~/.cache/go-build/
          ~/go/pkg/mod/
        key: go-${{ hashFiles('go.sum') }}
        restore-keys: |
          go-
    - name: Setup deps
      shell: bash
      run: |
        make install-build-deps