name: Publish ECR eksctl-build image

on: workflow_dispatch

permissions:
  id-token: write
  contents: read

jobs:
  build-and-push-to-registry:
    name: Build and push container image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b #v4.1.4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@010d0da01d0b5a38af31e9c3470dbfdabdecca3a # v4.0.1
        with:
          aws-region: us-east-1
          role-duration-seconds: 7200
          role-session-name: eksctl-build-ecr-publisher
          role-to-assume: ${{ secrets.ECR_PUBLISH_ROLE_ARN }}

      - name: Login to Amazon ECR Public
        id: login-ecr-public
        uses: aws-actions/amazon-ecr-login@062b18b96a7aff071d4dc91bc00c4c1a7945b076 # v1
        with:
          registry-type: public

      - name: Setup Go
        uses: actions/setup-go@0c52d547c9bc32b1aa3301fd7a9cb496313a4491 #v5.0.0
        with:
          go-version: 1.20.x
          cache: false

      - name: Cache go-build and mod
        uses: actions/cache@0c45773b623bea8c8e75f6c82b208c3cf94ea4f9 #v4.0.2
        with:
          path: |
            ~/.cache/go-build/
            ~/go/pkg/mod/
          key: go-${{ hashFiles('go.sum') }}
          restore-keys: |
            go-

      - name: Setup deps
        run: |
          make install-build-deps

      - name: Build and push image
        run: |
          PATH=$PATH:$(go env GOPATH)/bin make -f Makefile.docker push-build-image