name: Link checker

on:
  pull_request:
    paths:
      - 'userdocs/**'
      - '**.md'
  push:
    branches:
      - main
    paths:
      - 'userdocs/**'
      - '**.md'

jobs:
  link-checker:
    name: Check site links
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.9]
    steps:
      - uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b #v4.1.4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@82c7e631bb3cdc910f68e0081d67478d79c6982d #v5.1.0
        with:
          python-version: ${{ matrix.python-version }}
      - name: Setup Go
        uses: actions/setup-go@cdcb36043654635271a94b9a6d1392de5bb323a7 #v5.0.1
        with:
          go-version: 1.21.x
          cache: false
      - name: Install doc dependencies
        run: make install-site-deps
      - name: Build docs for link check
        run: make build-pages
        # Using link-checker action to check links in Markdown, HTML files
      - name: Link Checker
        uses: lycheeverse/lychee-action@2b973e86fc7b1f6b36a93795fe2c9c6ae1118621 #v1.10.0
        with:
          fail: true
          args: --exclude-all-private --exclude-mail --exclude-file .github/workflows/exclude-file.txt --verbose --no-progress './**/*.md' './**/*.html'
