name: Publish docs

on:
  release:
    types: [published]
jobs:
  publish-docs:
    name: Publish docs to Netlify
    if: ${{ !github.event.release.prerelease }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@9bb56186c3b09b4f86b1c65136769dd318469633 #v4.1.2
        with:
          token: ${{ secrets.EKSCTLBOT_TOKEN }}
          fetch-depth: 0
      - name: Setup build environment
        uses: ./.github/actions/setup-build
      - name: Setup identity as eksctl-bot
        uses: ./.github/actions/setup-identity
        with:
          token: "${{ secrets.EKSCTLBOT_TOKEN }}"
      - name: Trigger Netlify deployment
        run: make publish-docs
      - name: slack on success
        if: success()
        uses: actions-ecosystem/action-slack-notifier@fc778468d09c43a6f4d1b8cccaca59766656996a #v1.1.0
        with:
          slack_token: ${{ secrets.WEAVEWORKS_SLACK_EKSCTLBOT_TOKEN }}
          message: ":tada: Docs published successfully :tada:"
          channel: team-pitch-black
          color: green
          verbose: true
      - name: slack on failure
        if: failure()
        uses: actions-ecosystem/action-slack-notifier@fc778468d09c43a6f4d1b8cccaca59766656996a #v1.1.0
        with:
          slack_token: ${{ secrets.WEAVEWORKS_SLACK_EKSCTLBOT_TOKEN }}
          message: ":ahhhhhhhhh: Docs publishing failed."
          channel: team-pitch-black
          color: red
          verbose: true