name: Publish docs

on:
  release:
    types: [published]
jobs:
  publish-docs:
    name: Publish docs to Netlify
    if: ${{ !github.event.release.prerelease }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b #v4.1.4
        with:
          token: ${{ secrets.EKSCTLBOT_TOKEN }}
          fetch-depth: 0
      - name: Setup Go
        uses: actions/setup-go@cdcb36043654635271a94b9a6d1392de5bb323a7 #v5.0.1
        with:
          go-version: 1.20.x
          cache: false
      - name: Cache go-build and mod
        uses: actions/cache@0c45773b623bea8c8e75f6c82b208c3cf94ea4f9 #v4.0.2
        with:
          path: |
            ~/.cache/go-build/
            ~/go/pkg/mod/
          key: go-${{ hashFiles('go.sum') }}
          restore-keys: |
            go-
      - name: Setup identity as eksctl-bot
        uses: ./.github/actions/setup-identity
        with:
          token: "${{ secrets.EKSCTLBOT_TOKEN }}"
      - name: Trigger Netlify deployment
        run: make publish-docs
      - name: slack on success
        if: success()
        uses: actions-ecosystem/action-slack-notifier@fc778468d09c43a6f4d1b8cccaca59766656996a #v1.1.0
        with:
          slack_token: ${{ secrets.WEAVEWORKS_SLACK_EKSCTLBOT_TOKEN }}
          message: ":tada: Docs published successfully :tada:"
          channel: team-pitch-black
          color: green
          verbose: true
      - name: slack on failure
        if: failure()
        uses: actions-ecosystem/action-slack-notifier@fc778468d09c43a6f4d1b8cccaca59766656996a #v1.1.0
        with:
          slack_token: ${{ secrets.WEAVEWORKS_SLACK_EKSCTLBOT_TOKEN }}
          message: ":ahhhhhhhhh: Docs publishing failed."
          channel: team-pitch-black
          color: red
          verbose: true