name: Release

on:
  workflow_dispatch: {}

jobs:
  rc:
    name: Trigger release build
    runs-on: ubuntu-latest
    container: public.ecr.aws/eksctl/eksctl-build:c1ae010fa4b927d123afc6fdd7df07203aa40dd8
    steps:
      - name: Checkout
        uses: actions/checkout@9bb56186c3b09b4f86b1c65136769dd318469633 #v4.1.2
        with:
          token: ${{ secrets.EKSCTLBOT_TOKEN }}
          fetch-depth: 0
      - name: Cache go-build and mod
        uses: actions/cache@704facf57e6136b1bc63b828d79edcd491f0ee84 #v3.3.2
        with:
          path: |
            ~/.cache/go-build/
            ~/go/pkg/mod/
          key: go-${{ hashFiles('go.sum') }}
          restore-keys: |
            go-
      - name: Setup identity as eksctl-bot
        uses: ./.github/actions/setup-identity
        with:
          token: "${{ secrets.EKSCTLBOT_TOKEN }}"
      - name: Push tag and open PR to default branch
        run: make prepare-release
